### PR TITLE
Add oryx downloader (graphql query + unzip)

### PR DESCRIPTION
**Pull request by Phoscur**
This is a first step towards #1 proposing a few new conventions concerning folder structure. 

Will be followed up by adding more configurability (through env).

@gittyeric I don't think it's worth cleaning up the git history and moving my own macros out, are you okay with having my-macros.ts in there redundantly for now?

### CODE REVIEW

**Comment by eric-fulfil** [comment]
@phoscur yeah that works.  The only value in the hardcoded macros is to serve as a quickstart example to people, so other than having some breadth it doesn't matter much.

**Review by eric-fulfil — APPROVED** [review]
Super slick you were able to reverse engineer their Onyx interface!

**Comment by Phoscur** [comment]
> Super slick you were able to reverse engineer their Onyx interface!

Yeah, first I wanted to use cheerio to parse the HTML, but as that is not actually delivered prerendered by ORYX, I took a look at the other requests and found an extensive GraphQL API, which is easy to use.

**Comment by Phoscur** [comment]
@eric-fulfil plans on merging this? the other PR (#6) includes it aswell.

**Review by eric-fulfil — APPROVED** [review]
Sorry I had approved at some point.  Looks like you have to be the one to hit the merge button.

**Comment by gittyeric** [comment]
Nope, wrong account on my part!

**Comment by Phoscur** [comment]
Not fixing conflicts, since these changes are included in the other PR aswell

**Pull request closed without merging**
